title: Will Jump
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
url: "https://wontjump.github.io"
baseurl: ""
lang: en-GB
timezone: Asia/Singapore

author:
  name: Will Jump
  email: jumpwillem@gmail.com
  github: WontJump

permalink: /writing/:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      math: true

exclude:
  - AUTHORING.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
